FROM docker.io/library/ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        foot \
        waypipe \
        weston \
        xterm \
    && rm -rf /var/lib/apt/lists/*

CMD ["foot"]
