name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install dependencies
        run: brew install libxkbcommon pixman pkg-config

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run tests
        run: cargo test --workspace --locked

      - name: Build release binaries
        run: cargo build --release --bins --locked
